/**
 * Collective Intelligence Types
 *
 * Hierarchical knowledge compression system (L1-L4):
 * - L1: Document chunks (~500 tokens) - defined in knowledge.ts
 * - L2: Document summaries (~200 tokens)
 * - L3: Topic clusters across documents
 * - L4: Knowledge graph (concepts + relationships)
 */

// =============================================================================
// L2: DOCUMENT SUMMARIES
// =============================================================================

export type DocumentType =
  | 'prd'
  | 'meeting_notes'
  | 'research'
  | 'spec'
  | 'design'
  | 'feedback'
  | 'decision'
  | 'announcement'
  | 'other'

export type Sentiment = 'positive' | 'neutral' | 'negative' | 'mixed'

export interface DocumentSummary {
  id: string
  documentId: string
  summary: string
  keyPoints: string[]
  topics: string[]
  entities: string[]
  documentType: DocumentType | null
  sentiment: Sentiment | null
  complexityScore: number | null
  embedding: number[] | null
  modelUsed: string | null
  tokenCount: number | null
  generatedAt: string
  qualityScore: number | null
  feedbackCount: number
  createdAt: string
  updatedAt: string
}

export interface DocumentSummaryInsert {
  documentId: string
  summary: string
  keyPoints?: string[]
  topics?: string[]
  entities?: string[]
  documentType?: DocumentType
  sentiment?: Sentiment
  complexityScore?: number
  embedding?: number[]
  modelUsed?: string
  tokenCount?: number
  qualityScore?: number
}

// =============================================================================
// L3: TOPIC CLUSTERS
// =============================================================================

export type TopicCategory =
  | 'feature'
  | 'process'
  | 'decision'
  | 'research'
  | 'risk'
  | 'goal'
  | 'problem'
  | 'solution'
  | 'other'

export interface KnowledgeTopic {
  id: string
  teamId: string
  workspaceId: string | null
  name: string
  description: string | null
  summary: string | null
  category: TopicCategory | null
  importanceScore: number
  confidenceScore: number
  keywords: string[]
  relatedEntities: string[]
  embedding: number[] | null
  documentCount: number
  chunkCount: number
  lastUpdatedAt: string | null
  autoGenerated: boolean
  needsReview: boolean
  createdAt: string
  updatedAt: string
}

export interface KnowledgeTopicInsert {
  teamId: string
  workspaceId?: string
  name: string
  description?: string
  summary?: string
  category?: TopicCategory
  importanceScore?: number
  confidenceScore?: number
  keywords?: string[]
  relatedEntities?: string[]
  embedding?: number[]
  autoGenerated?: boolean
}

export interface TopicDocument {
  id: string
  topicId: string
  documentId: string
  relevanceScore: number
  createdAt: string
}

export interface TopicDocumentInsert {
  topicId: string
  documentId: string
  relevanceScore?: number
}

// =============================================================================
// L4: KNOWLEDGE GRAPH
// =============================================================================

export type ConceptType =
  | 'entity'
  | 'process'
  | 'decision'
  | 'goal'
  | 'metric'
  | 'risk'
  | 'person'
  | 'product'
  | 'technology'
  | 'other'

export type RelationshipType =
  | 'depends_on'
  | 'part_of'
  | 'related_to'
  | 'contradicts'
  | 'supports'
  | 'causes'
  | 'blocks'
  | 'influences'
  | 'owned_by'
  | 'uses'

export interface KnowledgeConcept {
  id: string
  teamId: string
  workspaceId: string | null
  name: string
  description: string | null
  conceptType: ConceptType
  attributes: Record<string, unknown>
  aliases: string[]
  embedding: number[] | null
  sourceDocuments: string[]
  mentionCount: number
  firstSeenAt: string
  lastSeenAt: string
  confidenceScore: number
  verified: boolean
  createdAt: string
  updatedAt: string
}

export interface KnowledgeConceptInsert {
  teamId: string
  workspaceId?: string
  name: string
  description?: string
  conceptType: ConceptType
  attributes?: Record<string, unknown>
  aliases?: string[]
  embedding?: number[]
  sourceDocuments?: string[]
  confidenceScore?: number
}

export interface ConceptRelationship {
  id: string
  sourceConceptId: string
  targetConceptId: string
  relationshipType: RelationshipType
  strength: number
  description: string | null
  evidence: string[]
  sourceDocuments: string[]
  autoGenerated: boolean
  verified: boolean
  createdAt: string
}

export interface ConceptRelationshipInsert {
  sourceConceptId: string
  targetConceptId: string
  relationshipType: RelationshipType
  strength?: number
  description?: string
  evidence?: string[]
  sourceDocuments?: string[]
  autoGenerated?: boolean
}

// =============================================================================
// COMPRESSION JOBS
// =============================================================================

/**
 * Valid compression job types - single source of truth for both type and validation
 */
export const COMPRESSION_JOB_TYPES = [
  'l2_summary',
  'l3_clustering',
  'l4_extraction',
  'full_refresh',
  'mindmap_embed', // Phase 5: BlockSuite mind map embedding
] as const

/**
 * Compression job type derived from const array - ensures type and validation stay in sync
 */
export type CompressionJobType = (typeof COMPRESSION_JOB_TYPES)[number]

/**
 * Type guard for runtime validation of compression job types
 */
export function isValidCompressionJobType(value: unknown): value is CompressionJobType {
  return typeof value === 'string' && COMPRESSION_JOB_TYPES.includes(value as CompressionJobType)
}

export type CompressionJobStatus = 'pending' | 'running' | 'completed' | 'failed'

export interface CompressionJob {
  id: string
  teamId: string
  workspaceId: string | null
  jobType: CompressionJobType
  status: CompressionJobStatus
  documentIds: string[] | null
  topicIds: string[] | null
  progress: number
  itemsProcessed: number
  itemsTotal: number
  currentStep: string | null
  result: CompressionJobResult | null
  errorMessage: string | null
  startedAt: string | null
  completedAt: string | null
  durationMs: number | null
  triggeredBy: string | null
  createdAt: string
}

export interface CompressionJobInsert {
  teamId: string
  workspaceId?: string
  jobType: CompressionJobType
  documentIds?: string[]
  topicIds?: string[]
  triggeredBy?: string
}

export interface CompressionJobResult {
  summariesCreated?: number
  topicsCreated?: number
  topicsUpdated?: number
  conceptsExtracted?: number
  relationshipsCreated?: number
  tokensUsed?: number
  errors?: string[]
}

// =============================================================================
// COMPRESSED CONTEXT (Function Return Types)
// =============================================================================

export type CompressionLayer = 'L1' | 'L2' | 'L3' | 'L4'

export interface CompressedContextItem {
  layer: CompressionLayer
  sourceId: string
  sourceName: string
  content: string
  similarity: number
  tokenCount: number
}

export interface CompressedContext {
  items: CompressedContextItem[]
  totalTokens: number
  layers: {
    L1: number // chunk count
    L2: number // summary count
    L3: number // topic count
    L4: number // concept count
  }
}

// =============================================================================
// KNOWLEDGE GRAPH (Function Return Types)
// =============================================================================

export interface KnowledgeGraphNode {
  id: string
  name: string
  conceptType: ConceptType
  description: string | null
  mentionCount: number
}

export interface KnowledgeGraphEdge {
  sourceConceptId: string
  targetConceptId: string
  relationshipType: RelationshipType
  strength: number
}

export interface KnowledgeGraph {
  concepts: KnowledgeGraphNode[]
  relationships: KnowledgeGraphEdge[]
  stats: {
    totalConcepts: number
    totalRelationships: number
    topConceptTypes: Record<ConceptType, number>
    topRelationshipTypes: Record<RelationshipType, number>
  }
}

// =============================================================================
// API REQUEST/RESPONSE TYPES
// =============================================================================

// Get compressed context
export interface GetCompressedContextRequest {
  workspaceId?: string
  query: string
  maxTokens?: number
}

export interface GetCompressedContextResponse {
  context: CompressedContext
  queryId: string
  durationMs: number
}

// Get knowledge graph
export interface GetKnowledgeGraphRequest {
  workspaceId?: string
  conceptLimit?: number
}

export interface GetKnowledgeGraphResponse {
  graph: KnowledgeGraph
  durationMs: number
}

// Trigger compression job
export interface TriggerCompressionRequest {
  workspaceId?: string
  jobType: CompressionJobType
  documentIds?: string[]
  topicIds?: string[]
}

export interface TriggerCompressionResponse {
  job: CompressionJob
  message: string
}

// List compression jobs
export interface ListCompressionJobsRequest {
  workspaceId?: string
  status?: CompressionJobStatus
  limit?: number
}

export interface ListCompressionJobsResponse {
  jobs: CompressionJob[]
  total: number
}

// =============================================================================
// DISPLAY TYPES (for UI)
// =============================================================================

export interface TopicDisplay extends KnowledgeTopic {
  documents?: Array<{
    id: string
    name: string
    relevanceScore: number
  }>
}

export interface ConceptDisplay extends KnowledgeConcept {
  incomingRelationships?: Array<{
    sourceId: string
    sourceName: string
    type: RelationshipType
    strength: number
  }>
  outgoingRelationships?: Array<{
    targetId: string
    targetName: string
    type: RelationshipType
    strength: number
  }>
}

// =============================================================================
// CONFIGURATION
// =============================================================================

export const COMPRESSION_CONFIG = {
  // L2: Document summaries
  l2: {
    maxSummaryTokens: 200,
    maxKeyPoints: 5,
    maxTopics: 5,
    maxEntities: 10,
  },

  // L3: Topic clusters
  l3: {
    maxSummaryTokens: 500,
    minDocumentsPerTopic: 2,
    maxKeywords: 10,
    clusteringThreshold: 0.7,
  },

  // L4: Knowledge graph
  l4: {
    maxConceptsPerDocument: 20,
    maxRelationshipsPerConcept: 10,
    minConfidenceScore: 0.5,
  },

  // General
  embeddingModel: 'text-embedding-3-small',
  embeddingDimensions: 1536,
  similarityThreshold: 0.6,
} as const

// Relationship type labels for UI
export const RELATIONSHIP_LABELS: Record<RelationshipType, string> = {
  depends_on: 'Depends On',
  part_of: 'Part Of',
  related_to: 'Related To',
  contradicts: 'Contradicts',
  supports: 'Supports',
  causes: 'Causes',
  blocks: 'Blocks',
  influences: 'Influences',
  owned_by: 'Owned By',
  uses: 'Uses',
}

// Concept type labels for UI
export const CONCEPT_TYPE_LABELS: Record<ConceptType, string> = {
  entity: 'Entity',
  process: 'Process',
  decision: 'Decision',
  goal: 'Goal',
  metric: 'Metric',
  risk: 'Risk',
  person: 'Person',
  product: 'Product',
  technology: 'Technology',
  other: 'Other',
}

// Topic category labels for UI
export const TOPIC_CATEGORY_LABELS: Record<TopicCategory, string> = {
  feature: 'Feature',
  process: 'Process',
  decision: 'Decision',
  research: 'Research',
  risk: 'Risk',
  goal: 'Goal',
  problem: 'Problem',
  solution: 'Solution',
  other: 'Other',
}
